// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 PiTrac contributors
// detect.c -- threshold DAC, gated-HPF control, comparator. See detect.h.

#include "detect.h"
#include "board.h"
#include "adc_engine.h"
#include "power_fsm.h"
#include "pio_alloc.h"

#include "hardware/pwm.h"
#include "hardware/gpio.h"
#include "hardware/clocks.h"
#include "pico/stdlib.h"

#include "detect.pio.h"      // generated by pico_generate_pio_header()

#include <math.h>

static void detect_pio_init(void);   // forward decl; defined below detect_init()

static uint     s_pio_offset;
static bool     s_armed;
static uint32_t s_events, s_fragments;
static uint32_t s_coalesce_us = DETECT_COALESCE_US;

// Partially-assembled pass, while fragments are still arriving.
static bool     s_frag_open;
static uint64_t s_frag_last_end_us;
static detect_pass_t s_building;
static detect_pass_t s_last;
static bool     s_have_last;

static uint     s_slice_thr, s_chan_thr;
static uint16_t s_thr_level;
static float    s_vref = 3.3f;
static hpf_mode_t s_hpf = HPF_TRACK;

// ---------------------------------------------------------------------------

void detect_init(void) {
    // GPIO44 = slice 10 channel A. Resolved at runtime, never from a constant --
    // the hand-written slice numbers in this file's ancestor were wrong three
    // times out of four (see the note in board.h).
    //
    // *** GPIO36 (UART_TX) IS THE SAME SLICE AND CHANNEL. *** It coexists only
    // because it stays SIO/UART. See the high-bank collision table in board.h.
    s_slice_thr = pwm_gpio_to_slice_num(PIN_THRESHOLD_PWM);
    s_chan_thr  = pwm_gpio_to_channel(PIN_THRESHOLD_PWM);

    pwm_config c = pwm_get_default_config();
    pwm_config_set_wrap(&c, (uint16_t)DAC_TOP);
    pwm_config_set_clkdiv_int(&c, 1);          // 150 MHz / 1024 = 146.48 kHz
    pwm_init(s_slice_thr, &c, false);

    // Threshold starts at zero, i.e. the comparator trips on anything. That is
    // the safe direction: a threshold stuck HIGH would look like "no ball ever",
    // which is indistinguishable from a dead detector.
    s_thr_level = 0;
    pwm_set_chan_level(s_slice_thr, s_chan_thr, 0);

    // Hand the pad to the PWM block. Until this point safe_state.c has it as an
    // SIO output driven low.
    //
    // NOTE GPIO44 is also ADC4. adc_engine_init() deliberately never calls
    // adc_gpio_init() on it and ADC_VALID_MASK excludes ch4 -- sampling a pin
    // that is being driven as a digital output reads the driver, not a signal.
    gpio_set_function(PIN_THRESHOLD_PWM, GPIO_FUNC_PWM);
    pwm_set_enabled(s_slice_thr, true);

    // GPIO46: leave it exactly as safe_state.c set it -- SIO input, NO internal
    // pulls. R103 is an external 10K pull-up on an open-collector output; an
    // internal pull-down would fight it and an internal pull-up would weaken the
    // logic-0 level.
    gpio_set_dir(PIN_D_COMPARATOR, GPIO_IN);

    // GPIO33 stays wherever safe_state.c left it (low) until the rail is up.
    s_hpf = (gpio_get_out_level(PIN_HPF_TOGGLE) == HPF_SEL_TRACK) ? HPF_TRACK : HPF_HOLD;

    detect_pio_init();
}

// ---------------------------------------------------------------------------
// PIO transit timer
// ---------------------------------------------------------------------------

static void detect_pio_init(void) {
    // pio_alloc_init() has already set this block's GPIOBASE to 16. It must
    // have -- pio_set_gpio_base() refuses once a program is loaded, and we are
    // about to load one.
    hard_assert(pio_get_gpio_base(PIO_BLK_HIGH) == PIO_BASE_HIGH);

    s_pio_offset = pio_add_program(PIO_BLK_HIGH, &detect_transit_program);

    pio_sm_config c = detect_transit_program_get_default_config(s_pio_offset);

    // ABSOLUTE gpio numbers. The SDK translates them against the block's base
    // in pio_sm_set_config() (the `pinhi` mechanism) and returns
    // PICO_ERROR_BAD_ALIGNMENT if a pin is outside the window -- so passing 46
    // here is correct and passing 46-16=30 would be wrong.
    sm_config_set_in_pins(&c, PIN_D_COMPARATOR);   // index 0 for `wait ... pin`
    sm_config_set_jmp_pin(&c, PIN_D_COMPARATOR);

    // The count loop is 2 cycles per tick, so clock the SM at twice the tick
    // rate. 150 MHz / (2 x 1 MHz) = 75 exactly -- an integer divider, so there
    // is no fractional-divider jitter on the timebase.
    uint32_t sysclk = clock_get_hz(clk_sys);
    uint32_t div    = sysclk / (2u * DETECT_TICK_HZ);
    hard_assert(div * 2u * DETECT_TICK_HZ == sysclk);   // must divide exactly
    sm_config_set_clkdiv(&c, (float)div);

    // DELIBERATELY NOT calling pio_gpio_init() on GPIO46. That function claims
    // the pad's function mux for PIO, which is needed only to DRIVE a pin. Pad
    // inputs are distributed to every peripheral regardless of FUNCSEL, and
    // GPIO46 is an input we must never drive -- it is the LM393's open
    // collector, and driving it would fight R103 and the comparator both.
    pio_sm_init(PIO_BLK_HIGH, PIO_SM_DETECT, s_pio_offset, &c);
    pio_sm_set_enabled(PIO_BLK_HIGH, PIO_SM_DETECT, false);
    s_armed = false;
}

bool detect_arm(bool on) {
    if (on && !power_rails_ready()) return false;

    if (on) {
        pio_sm_set_enabled(PIO_BLK_HIGH, PIO_SM_DETECT, false);
        pio_sm_clear_fifos(PIO_BLK_HIGH, PIO_SM_DETECT);
        pio_sm_restart(PIO_BLK_HIGH, PIO_SM_DETECT);
        pio_sm_exec(PIO_BLK_HIGH, PIO_SM_DETECT, pio_encode_jmp(s_pio_offset));
        s_events = s_fragments = 0;
        s_frag_open = false;
        s_have_last = false;
    }
    pio_sm_set_enabled(PIO_BLK_HIGH, PIO_SM_DETECT, on);
    s_armed = on;
    return true;
}

bool     detect_armed(void)      { return s_armed; }
uint32_t detect_events(void)     { return s_events; }
uint32_t detect_fragments(void)  { return s_fragments; }
uint32_t detect_coalesce_us(void){ return s_coalesce_us; }
void     detect_set_coalesce_us(uint32_t us) { s_coalesce_us = us; }

bool detect_last_pass(detect_pass_t *out) {
    if (!s_have_last || !out) return false;
    *out = s_last;
    return true;
}

static void close_pass(void) {
    if (!s_frag_open) return;
    s_frag_open = false;
    s_last      = s_building;
    s_have_last = true;
    s_events++;
}

void detect_service(void) {
    // Drain everything waiting. Each word is one HIGH pulse; several in quick
    // succession are one ball seen through a comparator with no hysteresis.
    while (!pio_sm_is_rx_fifo_empty(PIO_BLK_HIGH, PIO_SM_DETECT)) {
        uint32_t ticks = pio_sm_get(PIO_BLK_HIGH, PIO_SM_DETECT);
        uint64_t now   = time_us_64();
        s_fragments++;

        uint32_t width_us = ticks + DETECT_PIO_OVERHEAD_TICKS;   // 1 tick = 1 us

        if (s_frag_open && (now - s_frag_last_end_us) <= (uint64_t)s_coalesce_us) {
            // Same event, seen again after a notch.
            //
            // transit_us accumulates the fragments' OWN widths and therefore
            // EXCLUDES the notches between them -- it is a lower bound on the
            // true transit, not an estimate of it.
            //
            // The tempting alternative, reconstructing the span from these
            // consumption timestamps, is fake precision: the RX FIFO is 4 deep
            // and the superloop drains it in a single pass, so every fragment
            // of one ball is typically read within a few microseconds of the
            // others regardless of when the edges actually occurred. `now` dates
            // the read, not the edge.
            //
            // So a fragmented pass does not get a trustworthy comparator
            // transit at all, and it should not pretend to. fragments > 1 is
            // the signal to use the ADC-derived transit for that pass, which is
            // immune to chatter because it works from the bump's own shape.
            // Measuring how far apart the two disagree is Phase 4's job.
            s_building.fragments++;
            s_building.raw_ticks  += ticks;
            s_building.transit_us += width_us;
            s_building.t_ms = to_ms_since_boot(get_absolute_time());
        } else {
            close_pass();
            s_building.seq             = s_events + 1;
            s_building.t_ms            = to_ms_since_boot(get_absolute_time());
            s_building.transit_us      = width_us;
            s_building.raw_ticks       = ticks;
            s_building.fragments       = 1;
            s_building.threshold_level = s_thr_level;
            s_frag_open = true;
        }
        s_frag_last_end_us = now;
    }

    // A pass is complete once nothing further has arrived for the coalesce
    // window. Doing it here rather than on the next fragment means a single
    // clean pulse is reported promptly instead of waiting for the next ball.
    if (s_frag_open && (time_us_64() - s_frag_last_end_us) > (uint64_t)s_coalesce_us)
        close_pass();
}

// --- Threshold DAC ---------------------------------------------------------

void detect_threshold_set_duty(float duty) {
    if (duty < 0.0f) duty = 0.0f;
    if (duty > 1.0f) duty = 1.0f;
    s_thr_level = (uint16_t)(duty * (float)(DAC_TOP + 1u) + 0.5f);
    if (s_thr_level > DAC_TOP) s_thr_level = (uint16_t)DAC_TOP;
    pwm_set_chan_level(s_slice_thr, s_chan_thr, s_thr_level);
    sleep_ms(DAC_SETTLE_MS);
}

void detect_threshold_set_volts(float v) {
    detect_threshold_set_duty((s_vref > 0.0f) ? (v / s_vref) : 0.0f);
}

float    detect_threshold_duty(void)  { return (float)s_thr_level / (float)(DAC_TOP + 1u); }
float    detect_threshold_volts(void) { return detect_threshold_duty() * s_vref; }
uint16_t detect_threshold_level(void) { return s_thr_level; }
void     detect_threshold_set_vref(float v) { if (v > 0.5f && v < 6.0f) s_vref = v; }
float    detect_threshold_vref(void)  { return s_vref; }

// --- Gated HPF -------------------------------------------------------------

bool detect_hpf_set(hpf_mode_t m) {
    if (!power_rails_ready()) return false;
    gpio_put(PIN_HPF_TOGGLE, (m == HPF_TRACK) ? HPF_SEL_TRACK : HPF_SEL_HOLD);
    s_hpf = m;
    return true;
}

void detect_hpf_safe_off(void) {
    gpio_put(PIN_HPF_TOGGLE, 0);
    s_hpf = (HPF_SEL_TRACK == 0) ? HPF_TRACK : HPF_HOLD;
}

hpf_mode_t  detect_hpf_mode(void) { return s_hpf; }
const char *detect_hpf_name(hpf_mode_t m) { return (m == HPF_TRACK) ? "TRACK" : "HOLD"; }

bool detect_comparator(void) { return gpio_get(PIN_D_COMPARATOR) != 0; }

// ---------------------------------------------------------------------------
// HPF polarity self-test.
//
// The discriminator is drift, and the two states differ by orders of magnitude:
//
//   TRACK  the node is pinned to 0 V through R96 2M. Op-amp bias (~10 pA) into
//          2M is ~20 uV. It does not move.
//   HOLD   the node is open. TMUX1219 off-leakage of order 1 nA into C81 330 nF
//          is ~3 mV/s at the node, x14.5 = ~44 mV/s at ADC5 = ~55 codes/s.
//
// So over a few seconds HOLD walks by tens to hundreds of codes and TRACK does
// not. Anything less than a clear separation is a hardware finding, not a
// firmware result, and the caller must say so rather than pick a winner.
// ---------------------------------------------------------------------------

static float sample_drift_v(uint32_t window_ms, float *out_mean_v) {
    // Let the mux settle and the HPF do whatever it is going to do first.
    sleep_ms(200);

    uint16_t code;
    if (!adc_ring_avg(ADC_CH_DETECT, 256, &code)) { if (out_mean_v) *out_mean_v = 0.0f; return -1.0f; }
    float first = adc_code_to_volts(code);
    float lo = first, hi = first, sum = first;
    uint32_t n = 1;

    uint32_t t0 = to_ms_since_boot(get_absolute_time());
    while (to_ms_since_boot(get_absolute_time()) - t0 < window_ms) {
        sleep_ms(50);
        if (!adc_ring_avg(ADC_CH_DETECT, 256, &code)) continue;
        float v = adc_code_to_volts(code);
        if (v < lo) lo = v;
        if (v > hi) hi = v;
        sum += v; n++;
    }
    if (out_mean_v) *out_mean_v = sum / (float)n;
    return hi - lo;
}

void detect_hpf_test(hpf_test_t *out, uint32_t window_ms) {
    if (!out) return;
    hpf_mode_t restore = s_hpf;

    detect_hpf_set(HPF_TRACK);
    out->track_drift_v = sample_drift_v(window_ms, &out->track_mean_v);

    detect_hpf_set(HPF_HOLD);
    out->hold_drift_v = sample_drift_v(window_ms, &out->hold_mean_v);

    detect_hpf_set(restore);

    if (out->track_drift_v < 0.0f || out->hold_drift_v < 0.0f) {
        out->ratio = 0.0f; out->conclusive = false; out->polarity_ok = false;
        return;
    }

    // Floor the denominator at one ADC LSB so a perfectly still TRACK trace does
    // not divide by zero and report an infinite, meaningless ratio.
    float floor_v = adc_code_to_volts(1);
    float denom   = (out->track_drift_v > floor_v) ? out->track_drift_v : floor_v;
    out->ratio    = out->hold_drift_v / denom;

    // 4x separation. The predicted separation is far larger, so this is a loose
    // bar deliberately -- it only has to beat noise, and demanding more would
    // turn an ambiguous board into a failed test.
    out->conclusive  = (out->ratio >= 4.0f) || (out->ratio <= 0.25f);
    out->polarity_ok = out->conclusive && (out->ratio >= 4.0f);
}

// ---------------------------------------------------------------------------
// Threshold / comparator cross-calibration.
// ---------------------------------------------------------------------------

void detect_threshold_sweep(threshold_sweep_t *out, float lo, float hi, uint16_t steps) {
    if (!out || steps == 0) return;
    uint16_t restore = s_thr_level;

    out->found = false;
    out->steps = steps;
    out->adc5_span_v = 0.0f;

    float adc_lo = 1e9f, adc_hi = -1e9f;
    bool  prev_high = false;
    bool  first = true;

    for (uint16_t i = 0; i <= steps; i++) {
        float duty = lo + (hi - lo) * ((float)i / (float)steps);
        detect_threshold_set_duty(duty);          // includes DAC_SETTLE_MS

        uint16_t code = 0;
        adc_ring_avg(ADC_CH_DETECT, 256, &code);
        float v = adc_code_to_volts(code);
        if (v < adc_lo) adc_lo = v;
        if (v > adc_hi) adc_hi = v;

        bool high = detect_comparator();

        // The comparator idles HIGH when the signal is above threshold. Sweeping
        // the threshold UP, the flip we want is high -> low: the point where the
        // threshold overtakes the resting signal. Record the first transition in
        // either direction so the caller can sweep whichever way it likes.
        if (!first && high != prev_high) {
            if (!out->found) {
                out->found          = true;
                out->flip_duty      = duty;
                out->flip_volts     = duty * s_vref;
                out->adc5_at_flip   = code;
                out->adc5_at_flip_v = v;
            }
        }
        prev_high = high;
        first = false;
    }

    // ADC5 movement across the whole sweep. With no target and a steady beam the
    // only thing changing is the threshold, so anything here is GPIO44 crosstalk
    // into the detect node -- the 146.5 kHz DAC carrier is only 42 kHz from the
    // 104.17 kHz optical carrier. Two RC poles predict ~120 dB of rejection, so
    // the expected answer is "nothing"; the point is to have measured it.
    out->adc5_span_v = adc_hi - adc_lo;

    pwm_set_chan_level(s_slice_thr, s_chan_thr, restore);
    s_thr_level = restore;
    sleep_ms(DAC_SETTLE_MS);
}
