// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 PiTrac contributors
// detect.c -- threshold DAC, gated-HPF control, comparator. See detect.h.

#include "detect.h"
#include "board.h"
#include "adc_engine.h"
#include "power_fsm.h"
#include "pio_alloc.h"

#include "hardware/pwm.h"
#include "hardware/gpio.h"
#include "hardware/clocks.h"
#include "pico/stdlib.h"

#include "detect.pio.h"      // generated by pico_generate_pio_header()

#include <math.h>

static void detect_pio_init(void);   // forward decl; defined below detect_init()
static void close_pass(void);        // fwd; defined with the pass log

static uint     s_pio_offset;
static bool     s_armed;
static uint32_t s_events, s_fragments, s_dropped;
static uint32_t s_coalesce_us = DETECT_COALESCE_US;

// Partially-assembled pass, while fragments are still arriving.
static bool     s_frag_open;
static uint64_t s_frag_last_end_us;
static detect_pass_t s_building;
static detect_pass_t s_last;
static bool     s_have_last;

static uint     s_slice_thr, s_chan_thr;
static uint16_t s_thr_level;
static float    s_vref = 3.3f;
static hpf_mode_t s_hpf = HPF_TRACK;

// ---------------------------------------------------------------------------

void detect_init(void) {
    // GPIO44 = slice 10 channel A. Resolved at runtime, never from a constant --
    // the hand-written slice numbers in this file's ancestor were wrong three
    // times out of four (see the note in board.h).
    //
    // *** GPIO36 (UART_TX) IS THE SAME SLICE AND CHANNEL. *** It coexists only
    // because it stays SIO/UART. See the high-bank collision table in board.h.
    s_slice_thr = pwm_gpio_to_slice_num(PIN_THRESHOLD_PWM);
    s_chan_thr  = pwm_gpio_to_channel(PIN_THRESHOLD_PWM);

    pwm_config c = pwm_get_default_config();
    pwm_config_set_wrap(&c, (uint16_t)DAC_TOP);
    pwm_config_set_clkdiv_int(&c, 1);          // 150 MHz / 1024 = 146.48 kHz
    pwm_init(s_slice_thr, &c, false);

    // Threshold starts at zero, i.e. the comparator trips on anything. That is
    // the safe direction: a threshold stuck HIGH would look like "no ball ever",
    // which is indistinguishable from a dead detector.
    s_thr_level = 0;
    pwm_set_chan_level(s_slice_thr, s_chan_thr, 0);

    // Hand the pad to the PWM block. Until this point safe_state.c has it as an
    // SIO output driven low.
    //
    // NOTE GPIO44 is also ADC4. adc_engine_init() deliberately never calls
    // adc_gpio_init() on it and ADC_VALID_MASK excludes ch4 -- sampling a pin
    // that is being driven as a digital output reads the driver, not a signal.
    gpio_set_function(PIN_THRESHOLD_PWM, GPIO_FUNC_PWM);
    pwm_set_enabled(s_slice_thr, true);

    // GPIO46: leave it exactly as safe_state.c set it -- SIO input, NO internal
    // pulls. R103 is an external 10K pull-up on an open-collector output; an
    // internal pull-down would fight it and an internal pull-up would weaken the
    // logic-0 level.
    gpio_set_dir(PIN_D_COMPARATOR, GPIO_IN);

    // GPIO33 stays wherever safe_state.c left it (low) until the rail is up.
    s_hpf = (gpio_get_out_level(PIN_HPF_TOGGLE) == HPF_SEL_TRACK) ? HPF_TRACK : HPF_HOLD;

    detect_pio_init();
}

// ---------------------------------------------------------------------------
// PIO transit timer
// ---------------------------------------------------------------------------

static void detect_pio_init(void) {
    // pio_alloc_init() has already set this block's GPIOBASE to 16. It must
    // have -- pio_set_gpio_base() refuses once a program is loaded, and we are
    // about to load one.
    hard_assert(pio_get_gpio_base(PIO_BLK_HIGH) == PIO_BASE_HIGH);

    s_pio_offset = pio_add_program(PIO_BLK_HIGH, &detect_transit_program);

    pio_sm_config c = detect_transit_program_get_default_config(s_pio_offset);

    // ABSOLUTE gpio numbers. The SDK translates them against the block's base
    // in pio_sm_set_config() (the `pinhi` mechanism) and returns
    // PICO_ERROR_BAD_ALIGNMENT if a pin is outside the window -- so passing 46
    // here is correct and passing 46-16=30 would be wrong.
    sm_config_set_in_pins(&c, PIN_D_COMPARATOR);   // index 0 for `wait ... pin`
    sm_config_set_jmp_pin(&c, PIN_D_COMPARATOR);

    // The count loop is 2 cycles per tick, so clock the SM at twice the tick
    // rate. 150 MHz / (2 x 1 MHz) = 75 exactly -- an integer divider, so there
    // is no fractional-divider jitter on the timebase.
    uint32_t sysclk = clock_get_hz(clk_sys);
    uint32_t div    = sysclk / (2u * DETECT_TICK_HZ);
    hard_assert(div * 2u * DETECT_TICK_HZ == sysclk);   // must divide exactly
    sm_config_set_clkdiv(&c, (float)div);

    // DELIBERATELY NOT calling pio_gpio_init() on GPIO46. That function claims
    // the pad's function mux for PIO, which is needed only to DRIVE a pin. Pad
    // inputs are distributed to every peripheral regardless of FUNCSEL, and
    // GPIO46 is an input we must never drive -- it is the LM393's open
    // collector, and driving it would fight R103 and the comparator both.
    pio_sm_init(PIO_BLK_HIGH, PIO_SM_DETECT, s_pio_offset, &c);
    pio_sm_set_enabled(PIO_BLK_HIGH, PIO_SM_DETECT, false);
    s_armed = false;
}

bool detect_arm(bool on) {
    if (on && !power_rails_ready()) return false;

    if (on) {
        pio_sm_set_enabled(PIO_BLK_HIGH, PIO_SM_DETECT, false);
        pio_sm_clear_fifos(PIO_BLK_HIGH, PIO_SM_DETECT);
        pio_sm_restart(PIO_BLK_HIGH, PIO_SM_DETECT);
        pio_sm_exec(PIO_BLK_HIGH, PIO_SM_DETECT, pio_encode_jmp(s_pio_offset));
        s_events = s_fragments = s_dropped = 0;
        s_frag_open = false;
        s_have_last = false;
    }
    if (!on) {
        // Close any pass still being assembled rather than dropping it silently.
        // It is real data; the operator disarmed mid-flight, which is not the
        // same thing as the pass never having happened.
        close_pass();
    }
    pio_sm_set_enabled(PIO_BLK_HIGH, PIO_SM_DETECT, on);
    s_armed = on;
    return true;
}

bool     detect_armed(void)      { return s_armed; }
uint32_t detect_events(void)     { return s_events; }
uint32_t detect_fragments(void)  { return s_fragments; }

// Words the PIO pushed that we never read.
//
// `push noblock` DISCARDS when the 4-deep RX FIFO is full -- deliberately, so a
// slow consumer can never stall the timer. But that makes the loss invisible to
// a counter of what was read, and the case where it happens is heavy chatter,
// which is precisely what the fragment count exists to measure. RXSTALL latches
// it in hardware; we drain the latch so the count is cumulative.
uint32_t detect_dropped(void) {
    uint32_t bit = 1u << (PIO_FDEBUG_RXSTALL_LSB + PIO_SM_DETECT);
    if (PIO_BLK_HIGH->fdebug & bit) {
        PIO_BLK_HIGH->fdebug = bit;      // write-1-to-clear
        s_dropped++;
    }
    return s_dropped;
}
uint32_t detect_coalesce_us(void){ return s_coalesce_us; }
void     detect_set_coalesce_us(uint32_t us) { s_coalesce_us = us; }

bool detect_last_pass(detect_pass_t *out) {
    if (!s_have_last || !out) return false;
    *out = s_last;
    return true;
}

// ---------------------------------------------------------------------------
// Pass log and waveform ring
// ---------------------------------------------------------------------------

static detect_pass_t s_log[DETECT_LOG_N];
static size_t   s_log_n, s_log_head;      // ring; head = next write slot
static detect_wave_t s_wave[DETECT_WAVE_N];
static size_t   s_wave_head, s_wave_n;
static float    s_path_mm;
static uint8_t  s_condition;

void    detect_set_path_mm(float mm) { s_path_mm = (mm > 0.0f) ? mm : 0.0f; }
float   detect_path_mm(void)         { return s_path_mm; }
void    detect_set_condition(uint8_t c) { s_condition = c; }
uint8_t detect_condition(void)       { return s_condition; }

size_t detect_log_count(void) { return s_log_n; }

const detect_pass_t *detect_log_at(size_t i) {
    if (i >= s_log_n) return NULL;
    size_t oldest = (s_log_n == DETECT_LOG_N) ? s_log_head : 0;
    return &s_log[(oldest + i) % DETECT_LOG_N];
}

void detect_log_clear(void) { s_log_n = s_log_head = 0; s_wave_n = s_wave_head = 0; }

const detect_wave_t *detect_wave_recent(size_t i) {
    if (i >= s_wave_n) return NULL;
    return &s_wave[(s_wave_head + DETECT_WAVE_N - 1u - i) % DETECT_WAVE_N];
}

const detect_wave_t *detect_wave_for(uint32_t seq) {
    for (size_t i = 0; i < s_wave_n; i++)
        if (s_wave[i].pass_seq == seq) return &s_wave[i];
    return NULL;
}

static void log_append(const detect_pass_t *p) {
    s_log[s_log_head] = *p;
    s_log_head = (s_log_head + 1u) % DETECT_LOG_N;
    if (s_log_n < DETECT_LOG_N) s_log_n++;
}

// ---------------------------------------------------------------------------
// detect_refine -- pull the bump back out of the ring and measure it by its own
// shape rather than against a fixed threshold.
// ---------------------------------------------------------------------------

static inline size_t us_to_samples(uint64_t us, uint32_t rate_hz) {
    return (size_t)((us * rate_hz) / 1000000u);
}

// `age_us` is how long ago the FALLING EDGE was, at the moment this runs.
//
// That parameter is the whole reason this function is correct. The window used
// to be anchored at k = 0, i.e. "the newest sample right now" -- but close_pass()
// fires from the coalesce timeout, so refine() runs at least DETECT_COALESCE_US
// after the fall, plus superloop latency. With a guard of half a transit, any
// transit shorter than about twice the coalesce window put the bump entirely
// outside the search range: at 40 m/s the transit is ~1 ms and the bump sat
// ~2 ms further back than the window reached. The result was not an error, it
// was a confident measurement of baseline noise.
static uint16_t refine(detect_pass_t *p, uint32_t cmp_transit_us, uint64_t age_us) {
    adc_ring_view_t v;
    if (!adc_ring_view(ADC_CH_DETECT, &v) || v.rate_hz == 0) return DQ_NO_ADC;

    p->adc_rate_khz = (uint16_t)(v.rate_hz / 1000u);

    size_t depth  = adc_ring_depth();
    size_t n_span = us_to_samples(cmp_transit_us, v.rate_hz);
    if (n_span < 4) n_span = 4;

    // Where the falling edge sits in the ring right now.
    size_t k_fall = us_to_samples(age_us, v.rate_hz);

    // Half a transit of guard either side -- widened to a full transit for a
    // chattered pass, because there transit_us is the SUM of fragment widths and
    // therefore understates the true span. Those are exactly the passes that
    // most need the ADC path, so they must not also get the tightest window.
    size_t guard = (p->fragments > 1) ? n_span : (n_span / 2u);

    size_t k_lo = (k_fall > guard) ? (k_fall - guard) : 0u;
    size_t k_hi = k_fall + n_span + guard;
    size_t base_k = k_hi + n_span;          // baseline region, older than the bump
    size_t base_n = 256;

    uint16_t q = DQ_OK;
    if (base_k + base_n >= depth) {
        // The bump plus its baseline does not fit in the 32.8 ms the ring holds.
        // Below about 1.4 m/s this is expected -- use `capture` for those.
        q |= DQ_WINDOW_CLIP;
        if (k_hi >= depth) k_hi = depth ? depth - 1u : 0u;
        if (k_lo > k_hi)   k_lo = k_hi;
        base_k = k_hi;
        base_n = (depth > k_hi + 1u) ? (depth - k_hi - 1u) : 1u;
        if (base_n > 256) base_n = 256;
    }

    // Baseline from BEFORE the bump, not a global minimum. ADC5 idles near 0 V
    // but wanders in TRACK and drifts in HOLD, so a global min would sit below
    // the local baseline and push the 50 % level down.
    uint32_t sum = 0;
    for (size_t i = 0; i < base_n; i++) sum += adc_ring_view_at(&v, base_k + i);
    uint16_t baseline = (uint16_t)(sum / (base_n ? base_n : 1u));

    // Peak over the window.
    uint16_t peak = 0; size_t peak_k = k_lo; uint16_t sat = 0;
    for (size_t k = k_lo; k <= k_hi; k++) {
        uint16_t s = adc_ring_view_at(&v, k);
        if (s >= DETECT_SAT_CODE) sat++;
        if (s > peak) { peak = s; peak_k = k; }
    }
    if (sat >= 2) q |= DQ_SATURATED;

    p->adc_baseline    = baseline;
    p->adc_peak        = (peak > baseline) ? (uint16_t)(peak - baseline) : 0u;
    p->adc_sat_samples = sat;

    if (peak <= baseline + 8u) return q | DQ_NO_CROSSING;   // no bump worth measuring

    // 50 % of the bump's OWN amplitude. Using (peak - baseline) is what makes
    // this independent of both amplitude and baseline drift.
    uint16_t half = (uint16_t)(baseline + (peak - baseline) / 2u);

    // Walk OUTWARD from the peak in both directions, bounded by the window.
    // Outward rather than inward from the edges, so a noise spike elsewhere
    // cannot capture the crossing and shorten the transit.
    //
    // peak > half strictly (guaranteed by the +8 test above), so neither loop can
    // terminate on its first step -- which is what makes rise_k >= peak_k+1 and
    // fall_k <= peak_k-1, and therefore makes the neighbour reads below in range.
    size_t rise_k = 0; bool rise_ok = false;
    for (size_t k = peak_k; k <= k_hi; k++) {          // backwards in time
        if (adc_ring_view_at(&v, k) < half) { rise_k = k; rise_ok = true; break; }
    }
    size_t fall_k = 0; bool fall_ok = false;
    for (size_t k = peak_k; k-- > k_lo; ) {            // forwards in time
        if (adc_ring_view_at(&v, k) < half) { fall_k = k; fall_ok = true; break; }
    }
    if (!rise_ok || !fall_ok) return q | DQ_NO_CROSSING;

    // Linear interpolation between the straddling pair, in units of samples.
    // At 250 ksps this turns 4 us of granularity into well under 1 us on a
    // smooth edge -- and the LPF guarantees the edge is smooth.
    float rise_f = (float)rise_k, fall_f = (float)fall_k;
    {
        uint16_t a = adc_ring_view_at(&v, rise_k);        // below half
        uint16_t b = adc_ring_view_at(&v, rise_k - 1u);   // above half
        if (b > a) rise_f = (float)rise_k - (float)(half - a) / (float)(b - a);
    }
    {
        uint16_t a = adc_ring_view_at(&v, fall_k);        // below half
        uint16_t b = adc_ring_view_at(&v, fall_k + 1u);   // above half
        if (b > a) fall_f = (float)fall_k + (float)(half - a) / (float)(b - a);
    }

    float span_samples = rise_f - fall_f;
    if (span_samples <= 0.0f) return q | DQ_NO_CROSSING;

    p->adc_transit_ns = (uint32_t)(span_samples * 1.0e9f / (float)v.rate_hz);

    // Asymmetry: a real ball bump is near-symmetric after a 4th-order LPF; a
    // hand or an insect is not. Free pulse-shape validation, and the number a
    // later rejection rule would key on.
    float mid = (rise_f + fall_f) * 0.5f;
    p->adc_asym_q8 = (int16_t)(((mid - (float)peak_k) / span_samples) * 256.0f);

    // Only now ask whether the DMA lapped us mid-analysis. If it did, every
    // number above is suspect and the honest answer is to say so.
    if (!adc_ring_view_valid(&v, base_k + base_n)) q |= DQ_RING_LAPPED;

    // Snapshot a decimated waveform for the most recent few passes.
    if (!(q & DQ_RING_LAPPED)) {
        detect_wave_t *w = &s_wave[s_wave_head];
        size_t want = k_hi - k_lo + 1u;
        size_t dec  = (want + DETECT_WAVE_LEN - 1u) / DETECT_WAVE_LEN;
        if (dec < DETECT_WAVE_DECIM) dec = DETECT_WAVE_DECIM;
        size_t out = 0;
        for (size_t k = k_lo; k + dec <= k_hi + 1u && out < DETECT_WAVE_LEN; k += dec) {
            uint32_t acc = 0;
            for (size_t j = 0; j < dec; j++) acc += adc_ring_view_at(&v, k + j);
            w->s[out++] = (uint16_t)(acc / dec);
        }
        // Ring order is newest-first; reverse so the array plots as time.
        for (size_t a = 0, b = out ? out - 1u : 0u; a < b; a++, b--) {
            uint16_t t = w->s[a]; w->s[a] = w->s[b]; w->s[b] = t;
        }
        w->pass_seq = p->seq;
        w->len      = (uint16_t)out;
        w->rate_hz  = (uint32_t)(v.rate_hz / dec);
        w->baseline = baseline;
        // Peak index AFTER the reversal, clamped rather than computed bare.
        // When the peak lands in a trailing partial decimation group,
        // (peak_k - k_lo)/dec can equal `out` -- and out-1-out underflows a
        // size_t, then wraps a uint16_t to 65535 and plots off-scale.
        {
            size_t pi = (peak_k >= k_lo) ? ((peak_k - k_lo) / dec) : 0u;
            w->peak_idx = (out == 0 || pi >= out) ? 0u : (uint16_t)(out - 1u - pi);
        }
        s_wave_head = (s_wave_head + 1u) % DETECT_WAVE_N;
        if (s_wave_n < DETECT_WAVE_N) s_wave_n++;
    }
    return q;
}

static void close_pass(void) {
    if (!s_frag_open) return;
    s_frag_open = false;

    s_building.condition = s_condition;
    if (s_building.fragments > 1) s_building.quality |= DQ_CHATTER;

    // How long ago the fall was. refine() needs this to find the bump: without
    // it the search window is anchored to "now", which is always at least one
    // coalesce window too late.
    uint64_t now = time_us_64();
    uint64_t age = (now > s_frag_last_end_us) ? (now - s_frag_last_end_us) : 0u;
    s_building.quality |= refine(&s_building, s_building.transit_us, age);

    s_last      = s_building;
    s_have_last = true;
    s_events++;
    log_append(&s_last);
}

// ---------------------------------------------------------------------------

bool detect_stats(uint8_t condition, detect_stats_t *out) {
    if (!out) return false;
    *out = (detect_stats_t){0};

    // Two passes: means, then standard deviations. Two passes rather than the
    // sum-of-squares shortcut because these are ~10^4 us values whose spread is
    // ~10 us, and Sum(x^2) - n*mean^2 cancels to nearly nothing in float.
    double cs = 0, as = 0, ps = 0;
    for (size_t i = 0; i < s_log_n; i++) {
        const detect_pass_t *p = detect_log_at(i);
        if (p->condition != condition) continue;
        if (p->quality & DQ_SATURATED) out->n_saturated++;
        if (p->quality & DQ_CHATTER)   out->n_chatter++;
        // Exclusions are about whether the ADC number is usable at all.
        // Saturated passes stay IN: their bias has the opposite sign, so they
        // bracket the truth rather than being noise -- but they are counted so
        // the operator can see them.
        if (p->quality & (DQ_NO_CROSSING | DQ_WINDOW_CLIP | DQ_RING_LAPPED | DQ_NO_ADC)
            || p->adc_transit_ns == 0) { out->n_excluded++; continue; }
        out->n++;
        cs += p->transit_us;
        as += p->adc_transit_ns / 1000.0;
        ps += p->adc_peak;
    }
    if (out->n == 0) return false;

    out->cmp_mean_us = (float)(cs / out->n);
    out->adc_mean_us = (float)(as / out->n);
    out->peak_mean   = (float)(ps / out->n);

    double cv = 0, av = 0;
    for (size_t i = 0; i < s_log_n; i++) {
        const detect_pass_t *p = detect_log_at(i);
        if (p->condition != condition) continue;
        if (p->quality & (DQ_NO_CROSSING | DQ_WINDOW_CLIP | DQ_RING_LAPPED | DQ_NO_ADC)
            || p->adc_transit_ns == 0) continue;
        double d1 = (double)p->transit_us - out->cmp_mean_us;
        double d2 = (p->adc_transit_ns / 1000.0) - out->adc_mean_us;
        cv += d1 * d1; av += d2 * d2;
    }
    if (out->n > 1) {
        out->cmp_sd_us = (float)sqrt(cv / (out->n - 1));
        out->adc_sd_us = (float)sqrt(av / (out->n - 1));
    }
    out->bias = (out->adc_mean_us > 0.0f)
              ? (out->cmp_mean_us / out->adc_mean_us - 1.0f) : 0.0f;
    return true;
}

void detect_service(void) {
    // Drain everything waiting. Each word is one HIGH pulse; several in quick
    // succession are one ball seen through a comparator with no hysteresis.
    while (!pio_sm_is_rx_fifo_empty(PIO_BLK_HIGH, PIO_SM_DETECT)) {
        uint32_t ticks = pio_sm_get(PIO_BLK_HIGH, PIO_SM_DETECT);
        uint64_t now   = time_us_64();
        s_fragments++;

        uint32_t width_us = ticks + DETECT_PIO_OVERHEAD_TICKS;   // 1 tick = 1 us

        if (s_frag_open && (now - s_frag_last_end_us) <= (uint64_t)s_coalesce_us) {
            // Same event, seen again after a notch.
            //
            // transit_us accumulates the fragments' OWN widths and therefore
            // EXCLUDES the notches between them -- it is a lower bound on the
            // true transit, not an estimate of it.
            //
            // The tempting alternative, reconstructing the span from these
            // consumption timestamps, is fake precision: the RX FIFO is 4 deep
            // and the superloop drains it in a single pass, so every fragment
            // of one ball is typically read within a few microseconds of the
            // others regardless of when the edges actually occurred. `now` dates
            // the read, not the edge.
            //
            // So a fragmented pass does not get a trustworthy comparator
            // transit at all, and it should not pretend to. fragments > 1 is
            // the signal to use the ADC-derived transit for that pass, which is
            // immune to chatter because it works from the bump's own shape.
            // Measuring how far apart the two disagree is Phase 4's job.
            s_building.fragments++;
            s_building.raw_ticks  += ticks;
            s_building.transit_us += width_us;
            s_building.t_ms = to_ms_since_boot(get_absolute_time());
        } else {
            close_pass();
            // Zero first: refine() short-circuits on DQ_NO_ADC without touching
            // adc_peak / adc_baseline / adc_sat_samples / adc_asym_q8, and those
            // would otherwise still hold the previous pass's values.
            s_building = (detect_pass_t){0};
            s_building.seq             = s_events + 1;
            s_building.t_ms            = to_ms_since_boot(get_absolute_time());
            s_building.transit_us      = width_us;
            s_building.raw_ticks       = ticks;
            s_building.fragments       = 1;
            s_building.threshold_level = s_thr_level;
            s_building.quality         = DQ_OK;
            s_building.adc_transit_ns  = 0;
            s_frag_open = true;
        }
        s_frag_last_end_us = now;
    }

    // A pass is complete once nothing further has arrived for the coalesce
    // window. Doing it here rather than on the next fragment means a single
    // clean pulse is reported promptly instead of waiting for the next ball.
    if (s_frag_open && (time_us_64() - s_frag_last_end_us) > (uint64_t)s_coalesce_us)
        close_pass();
}

// --- Threshold DAC ---------------------------------------------------------

void detect_threshold_set_duty(float duty) {
    if (duty < 0.0f) duty = 0.0f;
    if (duty > 1.0f) duty = 1.0f;
    s_thr_level = (uint16_t)(duty * (float)(DAC_TOP + 1u) + 0.5f);
    if (s_thr_level > DAC_TOP) s_thr_level = (uint16_t)DAC_TOP;
    pwm_set_chan_level(s_slice_thr, s_chan_thr, s_thr_level);
    sleep_ms(DAC_SETTLE_MS);
}

void detect_threshold_set_volts(float v) {
    detect_threshold_set_duty((s_vref > 0.0f) ? (v / s_vref) : 0.0f);
}

float    detect_threshold_duty(void)  { return (float)s_thr_level / (float)(DAC_TOP + 1u); }
float    detect_threshold_volts(void) { return detect_threshold_duty() * s_vref; }
uint16_t detect_threshold_level(void) { return s_thr_level; }
void     detect_threshold_set_vref(float v) { if (v > 0.5f && v < 6.0f) s_vref = v; }
float    detect_threshold_vref(void)  { return s_vref; }

// --- Gated HPF -------------------------------------------------------------

bool detect_hpf_set(hpf_mode_t m) {
    if (!power_rails_ready()) return false;
    gpio_put(PIN_HPF_TOGGLE, (m == HPF_TRACK) ? HPF_SEL_TRACK : HPF_SEL_HOLD);
    s_hpf = m;
    return true;
}

void detect_hpf_safe_off(void) {
    gpio_put(PIN_HPF_TOGGLE, 0);
    s_hpf = (HPF_SEL_TRACK == 0) ? HPF_TRACK : HPF_HOLD;
}

hpf_mode_t  detect_hpf_mode(void) { return s_hpf; }
const char *detect_hpf_name(hpf_mode_t m) { return (m == HPF_TRACK) ? "TRACK" : "HOLD"; }

bool detect_comparator(void) { return gpio_get(PIN_D_COMPARATOR) != 0; }

// ---------------------------------------------------------------------------
// HPF polarity self-test.
//
// The discriminator is drift, and the two states differ by orders of magnitude:
//
//   TRACK  the node is pinned to 0 V through R96 2M. Op-amp bias (~10 pA) into
//          2M is ~20 uV. It does not move.
//   HOLD   the node is open, so C81 integrates the switch leakage.
//
// MEASURED, board 1 2026-08-17: HOLD drifts ~11 mV/s at ADC5, TRACK ~1.9, for a
// ratio of about 6. Working back, 11 mV/s / 14.5 gain x C81 330 nF implies
// ~250 pA of TMUX1219 off-leakage.
//
// MEASURED, board 2 2026-08-21: HOLD ~2.3 mV/s -> ~52 pA, separation 2.9x. Same
// polarity, ~5x less leakage. THIS IS WHY THE RATIO IS NOT THE CRITERION: two
// good boards gave 6x and 2.9x for the same correct answer. What was identical on
// both is that the repeats of a level agreed (0.1-0.2 mV on board 2) while the
// levels differed by 17.8 mV -- a rank test, which is what conclusive() uses.
//
// The original comment here predicted ~44 mV/s from an assumed 1 nA. That was 4x
// pessimistic -- TI specs this part's leakage in the low hundreds of pA at room
// temperature, which is what a *precision* switch is for. The direction of the
// test was right but the MARGIN was overestimated, and the 4x conclusiveness bar
// below only just cleared. Do not tighten that bar on the assumption of a large
// separation; if anything, lengthen the window instead -- a floating node's drift
// grows with time and a pinned one's does not, so a longer window separates them
// further while a tighter threshold just makes the test brittle.
// ---------------------------------------------------------------------------

// Sample the ADC5 baseline: mean and peak-to-peak excursion over `window_ms`.
// Assumes the caller has already settled the node -- this does NOT settle.
static void sample_baseline(uint32_t window_ms, float *out_mean, float *out_drift) {
    uint16_t code;
    if (!adc_ring_avg(ADC_CH_DETECT, 256, &code)) {
        *out_mean = 0.0f; *out_drift = -1.0f; return;
    }
    float first = adc_code_to_volts(code);
    float lo = first, hi = first, sum = first;
    uint32_t n = 1;

    uint32_t t0 = to_ms_since_boot(get_absolute_time());
    while (to_ms_since_boot(get_absolute_time()) - t0 < window_ms) {
        sleep_ms(50);
        if (!adc_ring_avg(ADC_CH_DETECT, 256, &code)) continue;
        float v = adc_code_to_volts(code);
        if (v < lo) lo = v;
        if (v > hi) hi = v;
        sum += v; n++;
    }
    *out_mean  = sum / (float)n;
    *out_drift = hi - lo;
}

void detect_hpf_test(hpf_test_t *out, uint32_t window_ms) {
    if (!out) return;
    *out = (hpf_test_t){0};
    out->track_level = -1;

    int restore = gpio_get_out_level(PIN_HPF_TOGGLE);

    // Alternate the levels so an ordering artifact shows up as a disagreement
    // between the two repeats of the same level rather than as a fake result.
    for (int rep = 0; rep < 2; rep++) {
        for (int lvl = 0; lvl < 2; lvl++) {
            gpio_put(PIN_HPF_TOGGLE, lvl);
            sleep_ms(HPF_TEST_SETTLE_MS);      // >= 7 tau. See the header.
            sample_baseline(window_ms, &out->mean_v[lvl][rep], &out->drift_v[lvl][rep]);
        }
    }
    gpio_put(PIN_HPF_TOGGLE, restore);

    for (int lvl = 0; lvl < 2; lvl++)
        for (int rep = 0; rep < 2; rep++)
            if (out->drift_v[lvl][rep] < 0.0f) return;   // no ADC; nothing to say

    // Average the repeats, and take the magnitude: TRACK sits at ~0, HOLD walks
    // away from it in whichever direction the leakage happens to push.
    float m0 = fabsf((out->mean_v[0][0] + out->mean_v[0][1]) * 0.5f);
    float m1 = fabsf((out->mean_v[1][0] + out->mean_v[1][1]) * 0.5f);

    // The repeatability check. This is the test that the previous version lacked
    // and that would have caught its ordering bug immediately: if the two
    // measurements of ONE level differ by more than the two levels differ from
    // each other, then whatever is being measured is not a property of the level.
    float spread0 = fabsf(out->mean_v[0][0] - out->mean_v[0][1]);
    float spread1 = fabsf(out->mean_v[1][0] - out->mean_v[1][1]);
    float between = fabsf(m0 - m1);
    out->order_effect = (spread0 > between) || (spread1 > between);

    float big = (m0 > m1) ? m0 : m1;
    float sml = (m0 > m1) ? m1 : m0;
    float floor_v = adc_code_to_volts(4);          // a few LSB of noise floor
    out->separation = big / ((sml > floor_v) ? sml : floor_v);

    // NO-OVERLAP is the primary criterion, not the ratio.
    //
    // A fixed ratio bar is the wrong statistic here, and it rejected a good
    // measurement once already. HOLD is an INTEGRATOR: its displacement depends
    // on how long the test dwelt in that state and on temperature, so the ratio
    // is not a property of the board -- observed 2.8x and 3.8x on the same board
    // on the same day with the same (correct) polarity. What IS invariant is that
    // every TRACK reading falls below every HOLD reading, because TRACK is pinned
    // to a fixed point and HOLD is somewhere else entirely.
    //
    // So: require complete separation of the two repeats, plus a modest ratio to
    // keep noise from satisfying it. That is effectively a rank test, and it is
    // insensitive to the absolute magnitude the ratio bar was hostage to.
    float lo0 = fminf(fabsf(out->mean_v[0][0]), fabsf(out->mean_v[0][1]));
    float hi0 = fmaxf(fabsf(out->mean_v[0][0]), fabsf(out->mean_v[0][1]));
    float lo1 = fminf(fabsf(out->mean_v[1][0]), fabsf(out->mean_v[1][1]));
    float hi1 = fmaxf(fabsf(out->mean_v[1][0]), fabsf(out->mean_v[1][1]));
    bool no_overlap = (hi0 < lo1) || (hi1 < lo0);

    out->conclusive  = !out->order_effect && no_overlap && (out->separation >= 2.0f);
    if (out->conclusive) {
        out->track_level = (m0 < m1) ? 0 : 1;
        out->polarity_ok = (out->track_level == HPF_SEL_TRACK);
    }
}

// ---------------------------------------------------------------------------
// Threshold / comparator cross-calibration.
// ---------------------------------------------------------------------------

void detect_threshold_sweep(threshold_sweep_t *out, float lo, float hi, uint16_t steps) {
    if (!out || steps == 0) return;
    uint16_t restore = s_thr_level;

    out->found = false;
    out->steps = steps;
    out->adc5_span_v = 0.0f;

    float adc_lo = 1e9f, adc_hi = -1e9f;
    bool  prev_high = false;
    bool  first = true;

    for (uint16_t i = 0; i <= steps; i++) {
        float duty = lo + (hi - lo) * ((float)i / (float)steps);
        detect_threshold_set_duty(duty);          // includes DAC_SETTLE_MS

        uint16_t code = 0;
        adc_ring_avg(ADC_CH_DETECT, 256, &code);
        float v = adc_code_to_volts(code);
        if (v < adc_lo) adc_lo = v;
        if (v > adc_hi) adc_hi = v;

        bool high = detect_comparator();

        // The comparator idles HIGH when the signal is above threshold. Sweeping
        // the threshold UP, the flip we want is high -> low: the point where the
        // threshold overtakes the resting signal. Record the first transition in
        // either direction so the caller can sweep whichever way it likes.
        if (!first && high != prev_high) {
            if (!out->found) {
                out->found          = true;
                out->flip_duty      = duty;
                out->flip_volts     = duty * s_vref;
                out->adc5_at_flip   = code;
                out->adc5_at_flip_v = v;
            }
        }
        prev_high = high;
        first = false;
    }

    // ADC5 movement across the whole sweep. With no target and a steady beam the
    // only thing changing is the threshold, so anything here is GPIO44 crosstalk
    // into the detect node -- the 146.5 kHz DAC carrier is only 42 kHz from the
    // 104.17 kHz optical carrier. Two RC poles predict ~120 dB of rejection, so
    // the expected answer is "nothing"; the point is to have measured it.
    out->adc5_span_v = adc_hi - adc_lo;

    pwm_set_chan_level(s_slice_thr, s_chan_thr, restore);
    s_thr_level = restore;
    sleep_ms(DAC_SETTLE_MS);
}
